cdn:
  client: ${CDN_CLIENT:placeholder}
  allowedContentTypes: [ image/jpeg, image/png ]
  avatar:
    minWidthHeight: 128 # in px
    maxWidthHeight: 512 # in px
    widthHeightForSave: 256 # in px
  realEstatePhoto:
    minWidthHeight: 256 # in px
    maxWidthHeight: 5000 # in px
  multipart:
    maxFileSize: 1MB
    maxRequestSize: 25MB

cloudinary:
  cloudinaryUrl: ${CLOUDINARY_URL}