spring:
  datasource:
    url: jdbc:h2:mem:${spring.application.name};MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: false
    generate-ddl: false
    hibernate.ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    clean-disabled: false

scheduler:
  enabled: false

email:
  enabled: false

files:
  client: placeholder
