email:
  enabled: ${EMAIL_ENABLED:true}
  server:
    credentials:
      username: ${EMAIL_USERNAME}
      password: ${EMAIL_PASSWORD}
    network:
      host: smtp.gmail.com
      port: 587
    properties:
      mail.protocol: smtp
      mail.test-connection: true
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  debugMode:
    enabled: ${DEBUG_EMAIL_ENABLED:false}
    from: info@realtorconnect.com
    server:
      credentials:
        username: user
        password: user
      network:
        host: localhost
        port: 1025